stages:
- pull
- tests

pull:
  type: pull
  script:
  - docker pull jolicode/phaudit:latest

tests:
  type: tests
  script:
  - ./scripts/prepare.sh
  - ./scripts/tests.sh

clean:
  type: clean
  - docker run --rm -v $PWD:$PWD -w $PWD busybox rm -Rf vendor composer.lock
  when: always
