stages:
- pull
- tests
- clean

pull:
  type: pull
  script:
  - docker pull jolicode/phaudit:latest
  - docker pull composer/composer

tests:
  type: tests
  script:
  - ./scripts/prepare.sh
  - ./scripts/tests.sh

clean:
  type: clean
  script:
  - docker run --rm -v $PWD:$PWD -w $PWD busybox rm -Rf vendor composer.lock
  when: always
